"""
Pull the three Google Fonts into the repo so the app renders correctly offline.

Noto Nastaliq Urdu is the reason this matters: Android ships no Nastaliq face,
so a failed CDN request leaves the whole Urdu UI in a broken fallback.

Two things keep the payload small. Only the subsets the app uses are kept -
latin for the Latin faces, arabic for Nastaliq. And all three families are
served as variable fonts, so every requested weight resolves to one identical
file; those are downloaded once and declared with a font-weight range instead
of once per weight, which is a 3x saving on a payload the service worker has
to precache.
"""
import os
import re
import urllib.request

OUT_DIR = os.path.join("public", "fonts")
CSS_OUT = os.path.join("src", "fonts.css")

# A modern UA is required; with the default urllib UA Google serves ttf.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

FAMILIES = [
    ("Inter", "wght@400;500;600", {"latin"}),
    ("Sora", "wght@500;600;700", {"latin"}),
    ("Noto Nastaliq Urdu", "wght@400;500;600", {"arabic"}),
]

BLOCK = re.compile(
    r"/\*\s*(?P<subset>[\w-]+)\s*\*/\s*(?P<block>@font-face\s*\{[^}]*\})",
    re.S,
)
FAMILY_RE = re.compile(r"font-family:\s*'([^']+)'")
WEIGHT_RE = re.compile(r"font-weight:\s*(\d+)")
URL_RE = re.compile(r"url\((https://[^)]+\.woff2)\)")
RANGE_RE = re.compile(r"unicode-range:\s*([^;]+);")


def fetch(url):
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    rules = []
    total = 0

    for family, axis, subsets in FAMILIES:
        query = family.replace(" ", "+")
        css = fetch(
            f"https://fonts.googleapis.com/css2?family={query}:{axis}&display=swap"
        ).decode("utf-8")

        # url -> {name, subset, weights, unicode_range}
        faces = {}
        for match in BLOCK.finditer(css):
            subset = match.group("subset")
            if subset not in subsets:
                continue
            block = match.group("block")
            url = URL_RE.search(block).group(1)

            face = faces.setdefault(url, {
                "name": FAMILY_RE.search(block).group(1),
                "subset": subset,
                "weights": [],
                "range": RANGE_RE.search(block).group(1).strip(),
            })
            face["weights"].append(int(WEIGHT_RE.search(block).group(1)))

        for url, face in faces.items():
            slug = face["name"].lower().replace(" ", "-")
            filename = f"{slug}-{face['subset']}.woff2"
            data = fetch(url)
            with open(os.path.join(OUT_DIR, filename), "wb") as fh:
                fh.write(data)
            total += len(data)

            lo, hi = min(face["weights"]), max(face["weights"])
            weight = f"{lo} {hi}" if lo != hi else str(lo)
            print(f"  {filename:34s} {len(data) / 1024:7.1f} KB  weight {weight}")

            rules.append(
                "@font-face {\n"
                f"  font-family: '{face['name']}';\n"
                "  font-style: normal;\n"
                f"  font-weight: {weight};\n"
                "  font-display: swap;\n"
                f"  src: url(/fonts/{filename}) format('woff2');\n"
                f"  unicode-range: {face['range']};\n"
                "}"
            )

        print(f"{family}: {len(faces)} file(s)")

    header = (
        "/*\n"
        " * Self-hosted fonts. Generated by scripts/fetch_fonts.py - do not edit.\n"
        " *\n"
        " * Bundled rather than loaded from the Google CDN so the app renders\n"
        " * correctly with no network. Noto Nastaliq Urdu is the one that matters:\n"
        " * Android has no Nastaliq fallback, so a missing file would leave every\n"
        " * Urdu screen in a broken face.\n"
        " *\n"
        " * All three are variable fonts, so one file covers each weight range.\n"
        " */\n\n"
    )
    with open(CSS_OUT, "w", encoding="utf-8") as fh:
        fh.write(header + "\n\n".join(rules) + "\n")

    print(f"\nwrote {CSS_OUT} - {len(rules)} faces, {total / 1024:.0f} KB total")


if __name__ == "__main__":
    main()
